// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace Hellcooker
{
public static class GPGSIds
{
        public const string achievement_poiscaille_party = "CgkI_ND8rucOEAIQBw"; // <GPGSID>
        public const string achievement_bienvenue_en_enfer = "CgkI_ND8rucOEAIQAQ"; // <GPGSID>
        public const string achievement_faire__manger_ou_tre_mang = "CgkI_ND8rucOEAIQCQ"; // <GPGSID>
        public const string achievement_monstres_vegans = "CgkI_ND8rucOEAIQBg"; // <GPGSID>
        public const string achievement_viande_viande = "CgkI_ND8rucOEAIQBQ"; // <GPGSID>
        public const string achievement_hellcooker = "CgkI_ND8rucOEAIQCw"; // <GPGSID>
        public const string achievement_cuistot_en_herbe = "CgkI_ND8rucOEAIQAg"; // <GPGSID>
        public const string achievement_let_me_cook = "CgkI_ND8rucOEAIQCg"; // <GPGSID>
        public const string achievement_dbrouillard = "CgkI_ND8rucOEAIQCA"; // <GPGSID>
        public const string achievement_recettes_avaries = "CgkI_ND8rucOEAIQAw"; // <GPGSID>
        public const string achievement_rassasi_pour_linstant = "CgkI_ND8rucOEAIQBA"; // <GPGSID>

}
}
